### ISSUE TITLE
message

### ISSUE THREAD

**Issue by displexic** [aditineemkar/aditineemkar#1]
Hi, I'm a 15 year old software engineer from NZ. I can see that you have accomplished more than me from when I was 13 and getting into programming. I have a proposition for learning more about coding. Email me if you have the time.

**Comment by aditineemkar** [comment]
Hi!, Thanks for the appreciation!, but sorry I cant email u 🙂

**Comment by aditineemkar** [comment]
Hi!!, Thanks for the appreciation!, But sorry I cant email you🙂

> Hi, I'm a 15 year old software engineer from NZ. I can see that you have accomplished more than me from when I was 13 and getting into programming. I have a proposition for learning more about coding. Email me if you have the time.

**Comment by aditineemkar** [comment]
> Hi, I'm a 15 year old software engineer from NZ. I can see that you have accomplished more than me from when I was 13 and getting into programming. I have a proposition for learning more about coding. Email me if you have the time.

Hi!, Thanks for the appreciation!, but sorry I cant email u as I am nowadays busy in my academics and study

**Comment by displexic** [comment]
Same, hardly get any sleep. Good luck
